### ISSUE TITLE
FME Flow Charts enable unsupported feature in 2024.0 and 2024.0.1

### ISSUE THREAD

**Issue by TinoM** [safesoftware/helm-charts#100]
Hey, we just noticed that the current version of the 2024 flow charts already enable a feature, which is supported only by the 2024.1 core.
Deploying FME 2024.0 and FME Flow 2024.0.1 result in a constantly crashing FME Core:
`2024-04-10 16:19:17 Wed-10-Apr-2024 02:19:17.033 PM   INFORM   Core   393558 : Commencing startup of process "Core". This is attempt 1.
2024-04-10 16:19:17 Wed-10-Apr-2024 02:19:17.078 PM   INFORM   Thread-186   Core   WARNING: A command line option has enabled the Security Manager
2024-04-10 16:19:17 Wed-10-Apr-2024 02:19:17.078 PM   INFORM   Thread-186   Core   WARNING: The Security Manager is deprecated and will be removed in a future release
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.203 PM   INFORM   Thread-186   Core   Exception in thread "requesthandler" java.lang.IllegalArgumentException: No enum constant COM.safe.fmeserver.api.management.distributed.FMEEngineType.UTILITY
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at java.base/java.lang.Enum.valueOf(Unknown Source)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.api.management.distributed.FMEEngineType.valueOf(FMEEngineType.java:3)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.FMEEngineInstance.parseRegistrationRequest(FMEEngineInstance.java:832)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.TransformationManager.registerFmeEngine(TransformationManager.java:1765)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.TransformationManager.registerFMEEngine(TransformationManager.java:2000)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.TransformationRequestsDispatcher.registerFMEEngine(TransformationRequestsDispatcher.java:861)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.FMEServer.handleFMEEngineRegistrationRequest(FMEServer.java:352)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.RequestHandler.handleServerSocketChannelConnectRequest(RequestHandler.java:163)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at COM.safe.fmeserver.RequestHandlerBase.run(RequestHandlerBase.java:882)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.204 PM   INFORM   Thread-186   Core        at java.base/java.lang.Thread.run(Unknown Source)
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.541 PM   INFORM   Core   393656 : Process "Core" being restarted.
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.541 PM   INFORM   Core   393566 : Process "Core" waiting for process output listener threads to terminate...
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.541 PM   INFORM   Core   393569 : Process "Core" closing process stderr output stream
2024-04-10 16:19:31 Wed-10-Apr-2024 02:19:31.541 PM   INFORM   Core   393570 : Closed process stderr output stream`

So this is currently resulting in a faulty deployment:
`helm install fmeflow safesoftware/fmeflow --set fmeflow.image.tag=2024.0,deployment.port=80,deployment.useHostnameIngress=false,deployment.hostname=kubernetes.docker.internal`
`helm install fmeflow safesoftware/fmeflow --set fmeflow.image.tag=2024.0.1,deployment.port=80,deployment.useHostnameIngress=false,deployment.hostname=kubernetes.docker.internal`

This does work:
`helm install fmeflow safesoftware/fmeflow --set fmeflow.image.tag=2024.0.1,deployment.port=80,deployment.useHostnameIngress=false,deployment.hostname=kubernetes.docker.internal,fmeflow.utilityengine.enabled=false`
`helm install fmeflow safesoftware/fmeflow --set fmeflow.image.tag=2024.1-beta,deployment.port=80,deployment.useHostnameIngress=false,deployment.hostname=kubernetes.docker.internal`

If you are going to deploy a FME Flow 2024.0, you'll have to explicitely disable the utility engine.

**Comment by TinoM** [comment]
Ah, okay, i just missed the new chart versioning. There is already  #99  ...

But i think it is not ideal that omitting the version defaults to 2.0.0 which is not compatible to the current stable container images.

**Comment by garnold54** [comment]
Thanks Tino! I agree with you. I do think no matter what we do it will be a bit clunky. But I'm leaning more towards not releasing higher version helm charts like this until they are the actual released version. It still would be nice for people to try out the betas as well though, especially if they wanted to test the upgrade before official release. I'm going to be thinking about this more. In the mean time I might remove the 2.0.0 version from this public repo for now so it doesn't cause more confusion.

My hope is longer term there won't be many cases of having to update the major version in this way. It just happened that 2024.1 has this difference in deployment that caused a breaking change in 2024.0 so we had to bump the helm chart version. Hopefully version 2.X of the chart will be compatible with many FME releases in the future.
